# NumPy Çalışma

### NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

In [3]:
np.array ([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [5]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [6]:
np.array([3.14, 4, 2, 13], dtype = "float")

array([ 3.14,  4.  ,  2.  , 13.  ])

In [7]:
# sifirdan array olusturma (np.zeros)

In [8]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# birlerden array olusturma (np.ones)

In [11]:
np.ones((3,4), dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
# belirlenen değerler ile doldurma (np.full)

In [14]:
np.full((3,5), 3, dtype="float")

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [15]:
np.arange(0,33,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
# code here (random.normal)
np.random.normal(size=(3,4))

array([[-1.49767693,  0.43450334,  0.80025095,  0.13837162],
       [ 0.96872666, -1.7800452 ,  0.94235007, -0.85791777],
       [-0.77915452,  2.2153376 ,  1.84071939,  0.0267319 ]])

In [18]:
# code here (random.randint)
np.random.randint(0, 9, size=(5,2))

array([[6, 0],
       [2, 3],
       [0, 4],
       [3, 3],
       [2, 7]])

### Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [19]:
import numpy as np

In [20]:
np.random.randint(low=2, high=10, size=10)

array([2, 5, 7, 3, 3, 5, 8, 4, 7, 9])

In [21]:
a = np.random.randint(10, size = 10)
a

array([7, 4, 1, 3, 0, 5, 6, 6, 5, 7])

In [22]:
# code here (find the dimension of a)
np.ndim(a)

1

In [23]:
# code here (find the shape of a)
np.shape(a)

(10,)

In [24]:
# code here (find the size of a)
np.size(a)

10

In [25]:
# code here (find the dtype of a)
a.dtype

dtype('int32')

In [26]:
# code here(assign your code to 'b', random.randint, hihg=20, size=(4,6))
b = np.random.randint(20, size=(4,6))
b

array([[ 6, 16,  0,  8, 19,  9],
       [19, 15,  6,  7,  1,  2],
       [16, 18,  1, 17, 17,  3],
       [15, 13,  1, 19,  8, 16]])

In [27]:
b

array([[ 6, 16,  0,  8, 19,  9],
       [19, 15,  6,  7,  1,  2],
       [16, 18,  1, 17, 17,  3],
       [15, 13,  1, 19,  8, 16]])

In [28]:
# code here (find the dimension of b)
np.ndim(b)

2

In [29]:
# code here (find the shape of b)
np.shape(b)

(4, 6)

In [30]:
# code here (find the size of b)
np.size(b)

24

In [31]:
# code here (find the dtype of b)
b.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [32]:
import numpy as np

In [33]:
# code here (arange, start=1, stop=10)
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# code here (reshape (3,3) your coding above)
np.reshape(a, newshape=(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a = np.arange(1,10)

In [36]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# code here (find the dimension of a)
a.ndim

1

In [38]:
# code here (reshape a as (1,9) and assign to b)
b = np.reshape(a, newshape=(1,9))

In [39]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
# code here (find the dimension of b)
b.ndim

2

### Array Birlestirme (Concatenation)

In [41]:
import numpy as np

In [42]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [43]:
# code here (concatenate x and y)
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [44]:
z = np.array([7,8,9])

In [45]:
# code here (concatenate x, y and z)
np.concatenate((x,y,z))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# code here (concatenate z, y and x)
np.concatenate((z,y,x))

array([7, 8, 9, 4, 5, 6, 1, 2, 3])

In [47]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [48]:
# code here (concatenate a and a)
np.concatenate((a,a))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
# code here (concatenate a and a)
np.concatenate((a,a), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [50]:
import numpy as np

In [51]:
x = np.array([1,2,3,99,99,3,2,1])

In [52]:
# code here (split x from 3 and 5)
np.split(x, (3,5))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [53]:
# code here (do a tuple unpacking for above splitting in order of a,b,c)
a, b, c = np.split(x, (3,5))


In [54]:
a, b, c

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [55]:
a

array([1, 2, 3])

In [56]:
b

array([99, 99])

In [57]:
c

array([3, 2, 1])

In [58]:
#iki boyutlu ayırma

In [59]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
# code here (split m)
np.split(m, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [61]:
# code here (split m)
np.split(m, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### Array Sıralama (Sorting)

In [62]:
import numpy as np

In [63]:
v = np.array([2,1,4,3,5])

In [64]:
v

array([2, 1, 4, 3, 5])

In [65]:
# code here (sort v)
np.sort(v)

array([1, 2, 3, 4, 5])

In [66]:
# iki boyutlu array siralama

In [67]:
m = np.random.normal(20,5, (3,3))

In [68]:
m

array([[18.57750179, 16.39421292, 17.3281998 ],
       [26.0414792 , 13.5915047 , 24.81421483],
       [17.70730203, 18.1999115 , 17.70486946]])

In [69]:
# code here (sort m)
np.sort(m)

array([[16.39421292, 17.3281998 , 18.57750179],
       [13.5915047 , 24.81421483, 26.0414792 ],
       [17.70486946, 17.70730203, 18.1999115 ]])

In [70]:
# code here (sort m)
np.sort(m, axis=0)

array([[17.70730203, 13.5915047 , 17.3281998 ],
       [18.57750179, 16.39421292, 17.70486946],
       [26.0414792 , 18.1999115 , 24.81421483]])

# Index ile Elemanlara Erişmek

In [71]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([6, 1, 8, 3, 7, 1, 1, 7, 1, 6])

In [72]:
# code here
a[1]

1

In [73]:
# code here
a[-3]

7

In [74]:
a[2], a[5], a[9] = [4, 0, 100]

In [75]:
# code here
a

array([  6,   1,   4,   3,   7,   0,   1,   7,   1, 100])

In [76]:
a[-2]

1

In [77]:
# code here
a[0]

6

In [78]:
# code here
a[-1]

100

In [79]:
m = np.random.randint(10, size = (3,5))
m

array([[0, 7, 1, 2, 9],
       [9, 5, 0, 7, 4],
       [5, 4, 1, 7, 9]])

In [80]:
# code here
m[0,1]

7

In [81]:
# code here
m[-1,-2]

7

In [82]:
# code here
m[1,4] = 9

In [83]:
m[1, 4]

9

In [84]:
# code here (look at the below array)
m

array([[0, 7, 1, 2, 9],
       [9, 5, 0, 7, 9],
       [5, 4, 1, 7, 9]])

In [85]:
m

array([[0, 7, 1, 2, 9],
       [9, 5, 0, 7, 9],
       [5, 4, 1, 7, 9]])

In [86]:
# code here
m[2,3] = 3

In [87]:
m[2, 3]

3

In [88]:
# code here (look at the below array)
m[-1,-2] = 111

In [89]:
m

array([[  0,   7,   1,   2,   9],
       [  9,   5,   0,   7,   9],
       [  5,   4,   1, 111,   9]])

In [90]:
m

array([[  0,   7,   1,   2,   9],
       [  9,   5,   0,   7,   9],
       [  5,   4,   1, 111,   9]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [91]:
import numpy as np

In [92]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [93]:
# code here
a[0:3]

array([20, 21, 22])

In [94]:
# code here
a[:3]

array([20, 21, 22])

In [95]:
# code here
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [96]:
# code here
a[np.mod(np.arange(a.size), 2) != 0]

array([21, 23, 25, 27, 29])

In [97]:
# code here
a[0:len(a):2]

array([20, 22, 24, 26, 28])

In [98]:
# code here
a[2:len(a):2]

array([22, 24, 26, 28])

In [99]:
# code here
a[0:len(a):3]

array([20, 23, 26, 29])

In [100]:
#iki boyutlu slice islemleri

In [101]:
m = np.random.randint(10, size = (5,5))

In [102]:
m

array([[4, 3, 5, 5, 9],
       [1, 6, 7, 9, 6],
       [8, 0, 0, 4, 9],
       [2, 2, 3, 1, 2],
       [6, 5, 8, 4, 6]])

In [103]:
# code here
m[::, 0:1]

array([[4],
       [1],
       [8],
       [2],
       [6]])

In [104]:
# code here
m[::, 1:2]

array([[3],
       [6],
       [0],
       [2],
       [5]])

In [105]:
m[::, 4]


array([9, 6, 9, 2, 6])

In [106]:
m

array([[4, 3, 5, 5, 9],
       [1, 6, 7, 9, 6],
       [8, 0, 0, 4, 9],
       [2, 2, 3, 1, 2],
       [6, 5, 8, 4, 6]])

In [107]:
# code here
m[0, ::]

array([4, 3, 5, 5, 9])

In [108]:
# code here
m[0, ::]

array([4, 3, 5, 5, 9])

In [109]:
# code here
m[1, ::]

array([1, 6, 7, 9, 6])

In [110]:
# code here
m[0:2, 0:3]

array([[4, 3, 5],
       [1, 6, 7]])

In [111]:
# code here
m[::, 0:2]

array([[4, 3],
       [1, 6],
       [8, 0],
       [2, 2],
       [6, 5]])

In [112]:
m

array([[4, 3, 5, 5, 9],
       [1, 6, 7, 9, 6],
       [8, 0, 0, 4, 9],
       [2, 2, 3, 1, 2],
       [6, 5, 8, 4, 6]])

In [113]:
# code here
m[1:3, 0:2]

array([[1, 6],
       [8, 0]])

# Alt Küme Üzerinde İşlem Yapmak

In [114]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[9, 4, 5, 7, 2],
       [7, 4, 5, 8, 3],
       [7, 9, 0, 7, 5],
       [9, 0, 6, 6, 5],
       [9, 6, 6, 2, 7]])

In [115]:
# code here
a[0:3, 0:2]

array([[9, 4],
       [7, 4],
       [7, 9]])

In [116]:
# code here
a[0:3, 0:2][0,0] = 4444
a[0:3, 0:2]

array([[4444,    4],
       [   7,    4],
       [   7,    9]])

In [117]:
a

array([[4444,    4,    5,    7,    2],
       [   7,    4,    5,    8,    3],
       [   7,    9,    0,    7,    5],
       [   9,    0,    6,    6,    5],
       [   9,    6,    6,    2,    7]])

In [118]:
m = np.random.randint(10, size = (5, 5))
m

array([[7, 0, 9, 8, 8],
       [4, 9, 9, 5, 9],
       [4, 8, 3, 6, 6],
       [1, 8, 2, 8, 1],
       [0, 0, 0, 9, 4]])

In [119]:
# code here
m[:3, :2]

array([[7, 0],
       [4, 9],
       [4, 8]])

In [120]:
# code here
m[:3, :2][0,0] = 9999
m[:3, :2]

array([[9999,    0],
       [   4,    9],
       [   4,    8]])

In [121]:
m

array([[9999,    0,    9,    8,    8],
       [   4,    9,    9,    5,    9],
       [   4,    8,    3,    6,    6],
       [   1,    8,    2,    8,    1],
       [   0,    0,    0,    9,    4]])

# Fancy Index ile Elemanlara Erişmek

In [122]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [123]:
# code here
v[1]

3

3

In [124]:
# code here
v[3]

9

9

In [125]:
# code here
v[5]

15

15

In [131]:
# code here
k= [1,3,5]
v[k]

array([ 3,  9, 15])

[3, 9, 15]

In [132]:
al_getir = [1,3,5]

In [133]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [134]:
# code here
v[al_getir]

array([ 3,  9, 15])

array([ 3,  9, 15])

In [256]:
#iki boyutta fancy

In [135]:
m = np.arange(9).reshape((3,3))

In [136]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [138]:
m[satir, sutun]

array([1, 5])

In [261]:
#basit index ile fancy index

In [139]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
m[0, [1,2]]

array([1, 2])

In [264]:
#slice ile fancy

In [141]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [142]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [143]:
v < 3

array([ True,  True, False, False, False])

In [144]:
v[v < 3]

array([1, 2])

In [ ]:
# code here

In [145]:
v[v > 3]

array([4, 5])

In [146]:
# code here
v[v>2]

array([3, 4, 5])

array([3, 4, 5])

In [147]:
# code here
v[v<4]

array([1, 2, 3])

array([1, 2, 3])

In [153]:
# code here
v[v==3]

array([3])

array([3])

In [161]:
# code here
v[(v>3) | (v<3)]

array([1, 2, 4, 5])

array([1, 2, 4, 5])

In [162]:
v

array([1, 2, 3, 4, 5])

In [163]:
# code here
v*2

array([ 2,  4,  6,  8, 10])

array([ 2,  4,  6,  8, 10])

In [164]:
# code here
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [166]:
# code here
v*v

array([ 1,  4,  9, 16, 25])

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

Bu bölüm bilgi ve tekrar maksatlı konulmuştur.

In [167]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [168]:
v - 1

array([0, 1, 2, 3, 4])

In [169]:
v * 5

array([ 5, 10, 15, 20, 25])

In [170]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [284]:
#ufunc

In [171]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [172]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [173]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [174]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [175]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [176]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [177]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [179]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [180]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [181]:
np.absolute(np.array([-3]))

array([3])

In [182]:
np.sin(360)

0.9589157234143065

In [183]:
np.cos(180)

-0.5984600690578581

In [184]:
v = np.array([1,2,3])

In [185]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [186]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [187]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [188]:
?np

# İstatistiksel Hesaplamalar

In [189]:
v

array([1, 2, 3])

In [190]:
np.mean(v)

2.0

In [191]:
v.sum()

6

In [192]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [307]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [193]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [194]:
a

array([[5, 1],
       [1, 3]])

In [195]:
b

array([12, 10])

In [196]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])